name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
      - run: |
          npm install
          npm run build

  publish-npm:
    name: Publish to NPM Registry
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
